### PR TITLE
Upgrade pgrx to 11.2

### PR DESCRIPTION
**Pull request by tomhoule**

### CODE REVIEW

**Comment by pksunkara** [comment]
You would need to update CI files too IIRC.

**Comment by tomhoule** [comment]
Indeed, I found a pgrx version reference in the Dockerfile and a github workflow. Fixed and pushed.

**Comment by gjtorikian** [comment]
👋 I'm hitting a similar version issue when running pgrx 0.11.3. Could I make a PR to relax the version checks here (`~0.11`, meaning, `>=0.11.0, <1.0.0`) ?

**Comment by pksunkara** [comment]
> Could I make a PR to relax the version checks here (~0.11, meaning, >=0.11.0, <1.0.0) ?

1. That would actually mean `>=0.11.0,<0.12.0`
2. If you set it to that in the repo and it works with 0.11.3, I don't mind merging it.

**Pull request merged**
