### PR TITLE
Add commutator

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Comment by workingjubilee** [comment]
If https://github.com/pgcentralfoundation/pgrx/pull/1261 lands in some form, you can land this with minimal changes. Until then, you could, I guess, define the pg_extern functions and annotate them with pg_operator macros by hand?

...yeah that's not great.

**Comment by pksunkara** [comment]
> If https://github.com/pgcentralfoundation/pgrx/pull/1261 lands in some form, you can land this with minimal changes. 

Thanks.

> Until then, you could, I guess, define the pg_extern functions and annotate them with pg_operator macros by hand?

Could you please point me to an example? I had trouble getting this working.

**Comment by workingjubilee** [comment]
I landed it, so pgrx 0.10.0 (or 0.10.0-beta.4, or whatever) will fix your code.

**Comment by pksunkara** [comment]
@workingjubilee Thank you for the help. Any timeline you guys are thinking for 0.10.0?

**Comment by workingjubilee** [comment]
To actually answer this question:

> Could you please point me to an example? I had trouble getting this working.

It would basically be like writing the fully-expanded, specific-type-instantiated version of this macro's inner contents:

https://github.com/pgcentralfoundation/pgrx/blob/159295238f7513da2e4c7075b004cf0b5a60d30b/pgrx-macros/src/operators.rs#L95-L114

But one might also have to correctly invoke the relevant parts of `pgrx-sql-entity-graph` to make it correctly create things like operator classes, etc. for the type, and it's all quite hellacious so I don't exactly recommend it.

**Pull request merged**
