### PR TITLE
Use pgrx 0.10.0-beta.4

### PR DESCRIPTION
**Pull request by workingjubilee**
I figured it may be convenient to draft a patch for use by anyone who may need a version patched to use the latest `pgrx`, whether or not the author of `pgx_ulid` intends to merge and publish this.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Though, I recommend actually cherry-picking whichever commits you want into the fixes-13 branch instead and making your own decisions, @pksunkara.

**Comment by workingjubilee** [comment]
For @osdiab: You may need to run `rustup update` or otherwise bump your installed Rust version, then you will want to `cargo install cargo-pgrx --version 0.10.0-beta.4`. Then you can use the usual array of packaging commands to build this extension.

**Comment by pksunkara** [comment]
@workingjubilee Thanks. I would have loved to merge or cherry-pick this but I don't intend to update the Rust version. Therefore, I am just updating the version in my PR.

**Comment by workingjubilee** [comment]
Ahh, I wasn't aware that it even would build with Rust 1.70.0, to be honest!

**Pull request closed without merging**
